kernel:
  image: linuxkit/kernel:4.14.48
  cmdline: "console=tty0 ipAddress=192.168.57.12 ipBroadcast=192.167.57.255 ipMask=24"
init:
  - wombat/init:dev
  - wombat/runc:dev
  - wombat/containerd:dev
  - wombat/ca-certificates:dev
  - wombat/getty:dev
onboot:
  - name: sysctl
    image: wombat/sysctl:dev
    binds:
     - /etc/sysctl.d/01-kubernetes.conf:/etc/sysctl.d/01-kubernetes.conf
    readonly: false
  - name: sysfs
    image: wombat/sysfs:dev
  - name: metadata
    image: wombat/metadata:dev
  - name: format
    image: wombat/format:dev
  - name: mounts
    image: wombat/mount:dev
    command: ["/usr/bin/mountie", "/var/lib/"]
  - name: dhcpcd
    image: wombat/dhcpcd:dev
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: bridge
    image: busybox:latest
    runtime:
      mkdir: ["/var/lib/cni/conf","/var/lib/cni/bin"]
services:
  - name: rngd
    image: wombat/rngd:dev
    cgroupsPath: systemreserved/rngd
  - name: ntpd
    image: wombat/openntpd:dev
    cgroupsPath: systemreserved/ntpd
  - name: sshd
    image: wombat/sshd:dev
    cgroupsPath: systemreserved/sshd
  - name: kubelet
    image: wombat/kubelet:dev
    cgroupsPath: podruntime/kubelet
files:
  - path: config/etc/matchbox
    directory: true
  - path: etc/linuxkit.yml
    metadata: yaml
  - path: etc/kubernetes
    symlink: "/var/lib/kubeadm"
  - path: etc/os-release
    contents: |
      PRETTY_NAME="Kubernit Project"
  - path: usr/libexec/kubernetes/kubelet-plugins
    symlink: "/var/lib/kubelet-plugins"
  - path: etc/kubeadm/
    directory: true
  - path: etc/sysctl.d/01-kubernetes.conf
    contents: 'net.ipv4.ip_forward = 1'
  - path: etc/cni/net.d
    directory: true
  - path: opt/cni/bin
    directory: true
  - path: root/.ssh/authorized_keys
    source: ~/.ssh/id_rsa.pub
    mode: "0600"
    optional: true
  - path: etc/kubelet.sh.conf
    contents: |
      KUBELET_ARGS="--container-runtime=remote --container-runtime-endpoint=unix:///run/containerd/containerd.sock"
  - path: run/config/cni.bridge/debug-show-configs
    contents: "1"
  - path: etc/kubeadm/kube-system.init/50-weave.yaml
    source: net.yaml
  - path: run/config/kubeadm/untaint-master
    contents: "1"
